name: Nightly Tests

on:
  schedule:
    - cron: '0 0 * * *'  # Runs at 00:00 UTC every day
  workflow_dispatch:  # Manual trigger option
  push:
    branches:
      - dev

env:
  DOCKER_LOGIN: ${{ secrets.DOCKER_LOGIN }}
  DOCKER_PASSWORD: ${{ secrets.DOCKER_PASSWORD }}

jobs:
  coverage:
    permissions: write-all
    runs-on: ubuntu-latest
    container:
      image: kaiachain/build_base:go1.23-solc0.8.13-ubuntu-22.04
    
    steps:
      - uses: actions/checkout@v4
      
      - name: Generate coverage report
        shell: bash
        run: |
          set -e
          git config --global --add safe.directory /__w/test-action/test-action
          export GOPATH=/go
          git clone --depth 1 https://$TEST_TOKEN@github.com/kaiachain/kaia-core-tests.git tests/testdata
          make cover
          mkdir -p /tmp/coverage_reports
          cp coverage_report.txt /tmp/coverage_reports/
          cp coverage_report.html /tmp/coverage_reports/
      
      - name: Upload coverage
        uses: codecov/codecov-action@v4
        with:
          token: ${{ secrets.CODECOV_TOKEN }} 